export const randomPrompts = [
  "A futuristic cityscape under a giant glass dome, with flying cars zipping between towering skyscrapers and holographic advertisements illuminating the sky.",
  "An astronaut riding a unicorn on Mars, with a backdrop of red mountains and an alien sky filled with multiple moons.",
  "A medieval castle floating in the sky, with dragons flying around it and waterfalls cascading from the edges into the clouds below.",
  "Robots playing chess in a Victorian-style room, with ornate furniture, a roaring fireplace, and a window showing a futuristic city outside.",
  "A steampunk airship sailing through clouds, with gears and steam engines visible, and a crew of adventurers in vintage pilot attire.",
  "A magical forest with glowing plants and creatures, where bioluminescent mushrooms light up the paths and fairies fly around casting sparkling spells.",
  "A panda bear playing a grand piano in a concert hall, with a full orchestra of animals and an audience of elegantly dressed wildlife.",
  "A pirate ship navigating through a sea of stars, with constellations forming the shape of mythical creatures and planets in the distance.",
  "A whimsical treehouse village at sunset, with interconnected bridges, lanterns hanging from branches, and children playing in the treetops.",
  "A mermaid exploring an underwater city, with coral buildings, fish swimming by, and ancient ruins covered in seaweed.",
  "A cyberpunk street market bustling with activity, neon lights reflecting off rain-soaked streets, and vendors selling high-tech gadgets and exotic foods.",
  "A dragon flying over a moonlit ocean, its scales glistening in the moonlight, with waves crashing below and a distant island in sight.",
  "A serene Japanese garden with cherry blossoms in full bloom, a koi pond with colorful fish, and a traditional tea house with sliding paper doors.",
  "A giant octopus wrapping its tentacles around a lighthouse during a storm, with lightning flashing and waves crashing against the rocks.",
  "A phoenix rising from the ashes in a mystical desert, with sand dunes glowing in the background and ancient ruins partially buried.",
  "An enchanted library with floating books, magical scrolls, and a wise old owl perched on a reading desk.",
  "A fairy sitting on a toadstool in a meadow, with a rainbow overhead, butterflies fluttering around, and a babbling brook nearby.",
  "A robot bartender mixing drinks in a neon-lit bar, with patrons that are a mix of humans and androids, and holographic decorations.",
  "A Viking warrior battling a sea serpent, with a stormy ocean, a longship in the background, and lightning illuminating the sky.",
  "A space station orbiting a colorful nebula, with astronauts conducting experiments, alien ships passing by, and a planet visible in the distance.",
  "A Victorian-era detective solving a mystery in a foggy London street, with gas lamps casting a dim glow and cobblestone roads slick with rain.",
  "A futuristic farm with robotic farmers tending to glowing crops, hovering drones monitoring the fields, and a domed greenhouse in the background.",
  "A dragon sleeping on a pile of treasure in a cave, with gold coins, jeweled artifacts, and ancient weapons scattered around.",
  "A samurai warrior meditating under a waterfall in a bamboo forest, with mist rising from the water and cherry blossoms falling gently.",
  "A space explorer discovering an alien temple on a distant planet, with strange symbols on the walls, glowing crystals, and a starry sky overhead.",
  "A fantasy castle made entirely of ice, with ice sculptures of mythical creatures, a frozen moat, and a blizzard swirling around.",
  "A futuristic city with buildings shaped like giant trees, connected by sky bridges, and lush greenery integrated into the architecture.",
  "A magical bakery where pastries float in the air, animated kitchen utensils bake on their own, and enchanted ingredients mix themselves.",
  "A group of pirates finding a hidden treasure cave, with glowing jewels, ancient artifacts, and a map showing more hidden locations.",
  "A medieval blacksmith forging a sword in a stone workshop, with sparks flying, molten metal pouring, and an anvil covered in runes.",
  "An alien jungle with plants that glow in the dark, strange creatures lurking in the foliage, and bioluminescent insects flying around.",
  "A steampunk inventor's workshop filled with gears, gadgets, and blueprints, with a half-built robot and steam-powered machines.",
  "A peaceful mountain village with log cabins, a crystal-clear lake, and snow-capped peaks in the background, during autumn with colorful leaves.",
  "A wizard's tower with potion bottles floating, spell books levitating, and a cauldron bubbling with a magical concoction.",
  "A futuristic underwater city with transparent domes, colorful fish swimming by, and high-tech submarines patrolling the area.",
  "A mystical portal in a dense forest, with glowing runes on ancient stones, and a view of another world through the portal.",
  "A surreal landscape with floating islands, waterfalls cascading into the sky, and strange creatures flying between the islands.",
  "A medieval banquet hall filled with knights and nobles, a feast laid out on long tables, and minstrels playing music.",
  "A sci-fi spaceship interior with sleek control panels, holographic displays, and a crew of diverse aliens and humans.",
  "A dreamlike scene of a whale flying through the clouds, with a city built on its back and birds flying alongside.",
  "A cybernetic dragon patrolling a high-tech metropolis, with neon lights reflecting off its metallic scales and skyscrapers towering overhead.",
  "A magical academy with students practicing spells, enchanted creatures roaming the grounds, and mystical towers in the background.",
  "A giant robot defending a futuristic city from an alien invasion, with laser beams, explosions, and spaceships in the sky.",
  "A tranquil Zen garden with meticulously raked sand, bonsai trees, and a monk meditating under a large stone lantern.",
  "A fantasy market with stalls selling enchanted items, magical potions, and exotic creatures, with bustling crowds and vibrant colors.",
  "A sci-fi laboratory where scientists are creating artificial life forms, with glowing tubes, advanced computers, and futuristic equipment.",
  "A fairy tale castle surrounded by an enchanted forest, with magical creatures like unicorns and griffins roaming the grounds.",
  "A steampunk city with airships docking at floating platforms, clockwork automatons walking the streets, and steam billowing from chimneys.",
  "A post-apocalyptic landscape with overgrown ruins, a makeshift village of survivors, and mutated creatures lurking in the shadows.",
  "A magical lighthouse on a cliff, with beams of light cutting through the night sky, guiding ships through a stormy sea.",
  "A space colony on a distant planet, with domed habitats, alien wildlife, and astronauts exploring the new world.",
  "A giant tree with houses built into its branches, rope bridges connecting them, and lanterns lighting the pathways.",
  "A mythical creature auction with various fantastical beings in cages, a bustling crowd of buyers, and a grand auctioneer.",
  "A superhero team posing on top of a skyscraper, with the city skyline behind them and their capes fluttering in the wind.",
  "A Victorian ballroom filled with elegantly dressed dancers, chandeliers hanging from the ceiling, and a grand staircase in the background.",
  "A cyberpunk biker gang racing through a neon-lit city, with futuristic motorcycles, glowing trails, and towering skyscrapers.",
  "A peaceful meadow with a rainbow, a unicorn grazing, and butterflies fluttering around, with a distant mountain range.",
  "A steampunk submarine exploring the depths of the ocean, with portholes showing strange sea creatures and underwater landscapes.",
  "A fantasy tavern filled with adventurers, a roaring fireplace, and a bard singing tales of heroism and magic.",
  "A futuristic park with robotic gardeners, holographic trees, and families enjoying the serene environment.",
  "A space pirate crew discovering a derelict spaceship, with mysterious artifacts, alien technology, and a sense of danger.",
  "A grand wizard casting a powerful spell in an ancient temple, with magical symbols glowing, and a dragon emerging from the shadows.",
  "A floating city with buildings suspended by balloons, airships docking at platforms, and people traveling in flying cars.",
  "A post-apocalyptic survivor scavenging through the ruins of a city, with overgrown buildings, abandoned vehicles, and wild animals.",
  "A mystical waterfall with glowing water, surrounded by enchanted trees, and mythical creatures drinking from the pool.",
  "A steampunk carnival with clockwork rides, a mechanical fortune teller, and performers in vintage attire.",
  "A space explorer encountering a giant alien creature, with bioluminescent patterns, an otherworldly landscape, and a spaceship in the background.",
  "A fantasy castle under a starry sky, with dragons flying around, knights patrolling the walls, and a grand ball taking place inside.",
  "A cyberpunk hacker's lair with multiple computer screens, neon lights, and a cityscape visible through the window.",
  "A peaceful Japanese village in winter, with snow-covered rooftops, a frozen pond, and people in traditional clothing.",
  "A futuristic racing event with flying cars, neon tracks, and spectators cheering from high-tech stands.",
  "A magical garden with animated flowers, talking animals, and a sparkling fountain at the center.",
  "A group of explorers finding an ancient temple in the jungle, with vines covering the entrance, mysterious carvings, and a sense of adventure.",
  "A serene beach at sunset, with palm trees, a hammock swaying in the breeze, and dolphins jumping out of the water.",
  "A post-apocalyptic market with traders selling salvaged goods, makeshift stalls, and a sense of resilience.",
  "A space princess overlooking her kingdom from a balcony, with a view of distant planets, stars, and her grand palace.",
  "A dragon perched on a mountain peak, with a panoramic view of the landscape below, including forests, rivers, and a distant castle.",
  "A whimsical candy land with gingerbread houses, candy cane trees, and rivers of chocolate, with children playing and exploring.",
  "A futuristic hospital with advanced medical technology, robotic doctors, and patients recovering in high-tech beds.",
  "A magical carnival with enchanted rides, mystical performers, and a grand fireworks display lighting up the night sky.",
  "A group of adventurers in a dark cave, with glowing crystals, ancient murals, and a sense of mystery and danger.",
  "A futuristic library with holographic books, robotic librarians, and a serene reading area with a view of the city.",
  "A medieval marketplace with bustling crowds, colorful stalls, and street performers entertaining passersby.",
  "A space explorer planting a flag on a newly discovered planet, with an alien landscape, distant stars, and a sense of accomplishment.",
  "A fairy tale cottage in the woods, with smoke rising from the chimney, a garden full of flowers, and woodland creatures nearby.",
  "A futuristic metropolis with towering skyscrapers, flying vehicles, and a bustling city life.",
  "A steampunk inventor demonstrating a new invention at a grand exhibition, with onlookers amazed by the mechanical marvel.",
  "A post-apocalyptic landscape with a lone wanderer, abandoned buildings, and a sense of desolation and hope.",
  "A magical library with books that come to life, enchanted scrolls, and a wise old wizard as the librarian.",
  "A peaceful village at dawn, with mist rising from the fields, birds singing, and villagers starting their day.",
  "A futuristic airport with sleek spaceships, passengers in high-tech attire, and a view of distant planets through the windows.",
  "A fantasy battlefield with knights and wizards clashing, dragons flying overhead, and a castle in the background.",
  "A whimsical bakery with floating pastries, animated kitchen tools, and a cheerful baker.",
  "A cyberpunk detective investigating a crime scene in a neon-lit alley, with rain-soaked streets and holographic advertisements.",
  "A tranquil mountain lake with crystal-clear water, surrounded by pine trees, and a small cabin on the shore.",
  "A magical workshop with enchanted tools, mystical artifacts, and a wizard creating potions and spells.",
];
